### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by cyb3rw0lf** [cyb3rw0lf/nepyh#1]
# ToDo list

## Logs
- [x] save session logs
- [x] show project logs at end of each config_gen()

## Error Handling:
- [x] Send error if YAML doesn't start with a list
- [x] YAML file not valid: pop up message to user, include link to yaml validator
- [x] Jinja2 file not found: pop up message to user
- [x] Jinja2 file not valid: pop up message to user
- [x] All other errors: save to session logs and pop up message to inform user

## GUI
- [ ] browse to last used directory
- [ ] copy/paste content for db/tp instead of files

## SW Upgrade menu
- [ ] check for new versions in git
- [ ] check if git is installed in local pc
- [ ] use git command to self upgrade (git pull)
- [ ] inform user with pop up message

## Help menu
- [x] YAML validation tool
- [x] Documentation
- [x] Git issues

## About menu
- [x] Author
- [x] Version
